### ISSUE TITLE
Syntax Error: Error: MainTemplate.hooks.hotBootstrap has been removed

### ISSUE THREAD

**Issue by AVargas89** [JBtje/vue3pdf#1]
Hi,

I am still getting this error when trying to use the component with vue3:

 error  in ./node_modules/pdfjs-dist-sig/es5/build/pdf.worker.js

Syntax Error: Error: MainTemplate.hooks.hotBootstrap has been removed (use your own RuntimeModule instead)

**Comment by JBtje** [comment]
Hi there,

Please provide a minimal project in which the error is present
or have a look here: https://github.com/JBtje/vue3pdf-demo for a working project usingVue3
