### ISSUE TITLE
Resize Sensor not working

### ISSUE THREAD

**Issue by zenflow** [JBtje/vue3pdf#2]
![image](https://user-images.githubusercontent.com/3198597/173970046-63769cd1-9abe-4612-a83d-e9dca7214540.png)

As you can see on the left side of the screenshot, resizing the width of the viewport is not properly accounted for.
As you can see on the right side of the screenshot, the element for the resize sensor has two attributes that weren't picked up as props by the `vue3-resize-sensor` component, and instead became [fallthrough attributes](https://vuejs.org/guide/components/attrs.html#attribute-inheritance), coerced into strings and applied to the component's root html element.

Problem is here: https://github.com/JBtje/vue3pdf/blob/1242adf4c82772314fce58f2cf9857d7b378ed4e/src/componentFactory.js#L25-L30

Not entirely sure but I think it's supposed to be something like this:

```
 initial: true, 
 onResize: this.resize, 
```

### Versions

- @jbtje/vue3pdf - 2.0.0
- vue - 3.2.36
- webpack - 5.72.1

**Comment by JBtje** [comment]
Thank you for providing the solution to the problem. I have verified it and it does solve the problem. The package has been updated!

**Comment by zenflow** [comment]
Wow! Great turnaround time! Thanks for fixing and for the package!
